package renegade.game;

public enum GamePhaseStep {
    START_PHASE,
    END_PHASE,

    COMMANDS_START_TURN,
    EXECUTE_COMMANDS,
    COMMANDS_END_TURN,

    COUNTERMEASURES_SMC_REVENGE,
    COUNTERMEASURES_SUCCESS_FAILURE,
    COUNTERMEASURES_SUCCESS_FAILURE_PLACE,
    COUNTERMEASURES_MOVE_SPARKS,
    COUNTERMEASURES_SCORING
}
